# Домашнее задание к уроку 1: Основы PyTorch

**Цель задания**

**Задание 1: Создание и манипуляции с тензорами (25 баллов)**


**1.1 Создание тензоров (7 баллов)**


In [ ]:
import torch
tensor1 = torch.rand(3, 4)
tensor2 = torch.zeros(2, 3, 4)
tensor3 = torch.ones(5, 5)
tensor4 = torch.arange(16).reshape(4, 4)
print(tensor1)
print(tensor2)
print(tensor3)
print(tensor4)

tensor([[0.3875, 0.5233, 0.9148, 0.6759],
        [0.8672, 0.9119, 0.8236, 0.6304],
        [0.3133, 0.0824, 0.1708, 0.4995]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


**1.2 Операции с тензорами (6 баллов)**

In [6]:
A = torch.rand(3, 4)
B = torch.rand(4, 3)
T_A = A.T #Транспонируем
dot = A @ B #Матричное умножение
mul = A * B.T #Поэлементное умножение
sm = A.sum() #Сумма всех элементов
print(A)
print(B)
print(T_A)
print(dot)
print(mul)
print(sm)

tensor([[0.8978, 0.1595, 0.3566, 0.3068],
        [0.7522, 0.1738, 0.1157, 0.3482],
        [0.9595, 0.5632, 0.6350, 0.5358]])
tensor([[0.8844, 0.7155, 0.7917],
        [0.3481, 0.7835, 0.8502],
        [0.9246, 0.6858, 0.8403],
        [0.7907, 0.8700, 0.1376]])
tensor([[0.8978, 0.7522, 0.9595],
        [0.1595, 0.1738, 0.5632],
        [0.3566, 0.1157, 0.6350],
        [0.3068, 0.3482, 0.5358]])
tensor([[1.4218, 1.2788, 1.1883],
        [1.1080, 1.0566, 0.8884],
        [2.0554, 2.0294, 1.8458]])
tensor([[0.7940, 0.0555, 0.3297, 0.2426],
        [0.5382, 0.1362, 0.0793, 0.3029],
        [0.7597, 0.4788, 0.5336, 0.0737]])
tensor(5.8041)


**1.3 Индексация и срезы (6 баллов)**

In [11]:
tensor = torch.arange(125).reshape(5, 5, 5) #матрица 5x5x5 от 0 до 124
first_row = tensor[0] #берем первую строку
last_col = tensor[:, :, -1] #берем последний столбец
cntr = tensor[2, 1:3, 1:3] #берем Подматрицу размером 2x2 из центра тензора
even = tensor[::2, ::2, ::2] #берем Все элементы с четными индексами
print(first_row)
print(last_col)
print(cntr)
print(even)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
tensor([[  4,   9,  14,  19,  24],
        [ 29,  34,  39,  44,  49],
        [ 54,  59,  64,  69,  74],
        [ 79,  84,  89,  94,  99],
        [104, 109, 114, 119, 124]])
tensor([[56, 57],
        [61, 62]])
tensor([[[  0,   2,   4],
         [ 10,  12,  14],
         [ 20,  22,  24]],

        [[ 50,  52,  54],
         [ 60,  62,  64],
         [ 70,  72,  74]],

        [[100, 102, 104],
         [110, 112, 114],
         [120, 122, 124]]])


**1.4 Работа с формами (6 баллов)**

In [10]:
ten = torch.randn(24)
nten1= ten.reshape(2, 12) #изменяем размер матрицы на 2x12
nten2 = ten.reshape(3, 8)
nten3  = ten.reshape(4, 6)
nten4 = ten.reshape(2, 3, 4)
nten5 = ten.reshape(2, 2, 2, 3)
print(nten1)
print(nten2)
print(nten3)
print(nten4)
print(nten5)

tensor([[-0.4246,  0.3795,  0.3515, -0.3642,  0.7468, -0.3539,  1.4591,  0.2743,
          0.1225,  2.4178,  0.8515,  1.4474],
        [ 1.4324, -0.5123, -1.7494,  0.0270, -0.0557,  0.5359, -0.6298,  1.1441,
         -0.1826,  0.6526, -1.7132, -1.2998]])
tensor([[-0.4246,  0.3795,  0.3515, -0.3642,  0.7468, -0.3539,  1.4591,  0.2743],
        [ 0.1225,  2.4178,  0.8515,  1.4474,  1.4324, -0.5123, -1.7494,  0.0270],
        [-0.0557,  0.5359, -0.6298,  1.1441, -0.1826,  0.6526, -1.7132, -1.2998]])
tensor([[-0.4246,  0.3795,  0.3515, -0.3642,  0.7468, -0.3539],
        [ 1.4591,  0.2743,  0.1225,  2.4178,  0.8515,  1.4474],
        [ 1.4324, -0.5123, -1.7494,  0.0270, -0.0557,  0.5359],
        [-0.6298,  1.1441, -0.1826,  0.6526, -1.7132, -1.2998]])
tensor([[[-0.4246,  0.3795,  0.3515, -0.3642],
         [ 0.7468, -0.3539,  1.4591,  0.2743],
         [ 0.1225,  2.4178,  0.8515,  1.4474]],

        [[ 1.4324, -0.5123, -1.7494,  0.0270],
         [-0.0557,  0.5359, -0.6298,  1.1441],
    